//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SReportLog
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SReport.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;body&gt;
        ///
        ///    &lt;div id=&quot;header&quot;&gt;
        ///        &lt;h1&gt;SReport&lt;/h1&gt;
        ///    &lt;/div&gt;
        ///
        ///    &lt;div id=&quot;nav&quot;&gt;
        ///        &lt;strong&gt;Failed tests:&lt;/strong&gt;
        ///        &lt;br&gt;
        ///        &lt;br&gt;
        ///        &lt;ul id=&quot;test-list&quot;&gt;
        ///            &lt;li class=&quot;test-last-name&quot;&gt;&lt;/li&gt;
        ///        &lt;/ul&gt;
        ///    &lt;/div&gt;
        ///
        ///    &lt;div id=&quot;section&quot;&gt;
        ///        &lt;span id=&quot;test-namespace&quot;&gt;&lt;/span&gt;
        ///        &lt;span id=&quot;test-last-name&quot;&gt;&lt;/span&gt;
        ///        &lt;span id=&quot;test-date-time&quot;&gt;&lt;/span&gt;
        ///        &lt;br&gt;
        ///        &lt;ul&gt;
        ///            &lt;li class=&quot;test-log-option&quot;&gt;&lt;/li&gt;
        ///        &lt;/ul&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sreport_template {
            get {
                return ResourceManager.GetString("sreport_template", resourceCulture);
            }
        }
    }
}
